### ISSUE TITLE
Add `protoc-gen-pulsar` and `protoc-gen-cosmos-gogo` plugins

### ISSUE THREAD

**Issue by julienrbrt** [bufbuild/plugins#1080]
Hi!

We were intending to use buf plugins for the Cosmos SDK, as we wanted to get the most of buf for us and blockchain developers. However, custom plugins are since short a paid feature only and open-source projects cannot create public custom plugins either.

Would it be possible to get official buf plugins for [protoc-gen-pulsar](https://github.com/cosmos/cosmos-proto) and [protoc-gen-cosmos-gogo](https://github/cosmos/gogoproto)?

ref: https://github.com/cosmos/cosmos-sdk/issues/11491#issuecomment-1961254548

**Comment by chrispine** [comment]
Thanks for this suggestion! Unfortunately, we are investing in other projects and directions at the moment, and will not be able to get to this.

**Comment by julienrbrt** [comment]
That's unfortunate, but thanks for the quick answer. If you ever change your mind, I'll be happy to submit a PR here for both plugins.
