### ISSUE TITLE
Update release of ts-proto?

### ISSUE THREAD

**Issue by melonmanchan** [bufbuild/plugins#1498]
Hi! I noticed that the latest version of stephenh-ts-proto on [buf](https://buf.build/community/stephenh-ts-proto) is lagging a bit behind on the official releases (currently at [v2.2.0)](https://github.com/stephenh/ts-proto/releases). Would it be posssible to ge buf updated? Thanks!

**Comment by mfridman** [comment]
Sure, we'll get that updated. This plugin is a bit aggressive on updates, and we have some future work to add an "interval" concept to update every week, month, etc.
