### ISSUE TITLE
Plugin request for Buf Schema Registry - grpc-gateway

### ISSUE THREAD

**Issue by bufdev** [bufbuild/plugins#152]
We should add grpc-gateway and special-case it to generate to a different package, similar to grpc-go. We should have special documentation around how to use grpc-gateway once we do so as well.

grpc-gateway requires:

- The golang base types
- The grpc-go types
- A dependency on googleapis, with the `go_package` values from googleapis used (this is an `except` when used with managed mode)

This means that the grpc-gateway plugin needs to be aware of the package for the golang base types, and the grpc-go types. Normally, this is the same package. However, we've split out grpc-go to be in a different package, so we need to communicate to the grpc-gateway plugin both the golang base type package, and the grpc-gateway package. This will take a change to grpc-gateway, either through a PR or through a patch, similar to grpc-go.

grpc-gateway recently added a `standalone=true` option, which when used, will generate grpc-gateway code to a different package than the golang base types and the grpc-go types. This is 90% of the battle - the general code to generate grpc-gateway types to a different package is already there. However, it still assumes the golang base types and grpc-go types are all in the same package. We would need to make it so that we can specify a seperate grpc-go type package.

If we do this, grpc-gateway will work with the go module proxy out of the box.

**Comment by mfridman** [comment]
In https://github.com/bufbuild/plugins/pull/262 we merged the **remote plugin**, but there is still outstanding to make it available as a **remote package**. Let's keep this issue open until that is resolved.
