### ISSUE TITLE
Plugin request for Buf Schema Registry: protoc-gen-nestjs

### ISSUE THREAD

**Issue by yukukotani** [bufbuild/plugins#199]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/yukukotani/protoc-gen-nestjs

## Optional

**Does the plugin have a valid semver version?**

v0.1.0 is the latest and it's from npm registry.

**Does the plugin have default options?**

no

**Does this plugin have runtime dependencies?**

It's depends on the generated code of protoc-gen-es, so `@bufbuild/protobuf` is required.

**Does the plugin have a dependency on another plugin?**

protoc-gen-es

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

npm registry

**Comment by yukukotani** [comment]
@pkwarren Sorry to bother you, but any progress on this?
We've used this internally and [this change](https://buf.build/docs/migration-guides/migrate-remote-generation-alpha/#public-plugins-are-now-solely-maintained-by-the-buf-team) breaks our workflow. We'd like to ship this as a public plugin.

Glad to do anything I should do to promote this.

**Comment by pkwarren** [comment]
Hi @yukukotani - I've asked the team about this plugin and should have an update for you next week. We've prioritized the highest used plugins for migration to this repo and this may have slipped through the cracks.

Also note that our teams and higher plans do support custom organization plugins (https://buf.build/pricing/), however I understand if that doesn't work for you.
