### ISSUE TITLE
Plugin request for Buf Schema Registry: mypy-protobuf

### ISSUE THREAD

**Issue by stefanvanburen** [bufbuild/plugins#219]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/nipunn1313/mypy-protobuf/tree/main/mypy_protobuf

## Optional

**Does the plugin have a valid semver version?**

Yes, currently `3.4.0`, from https://github.com/nipunn1313/mypy-protobuf/blob/main/CHANGELOG.md.

**Does this plugin have runtime dependencies?**

I think so, under ["Requirements to run mypy-protobuf"](https://github.com/nipunn1313/mypy-protobuf#requirements-to-run-mypy-protobuf).

**Does the plugin have a dependency on another plugin?**

Nope - it's commonly used with [`python-protobuf`](https://pypi.org/project/protobuf/), but isn't dependent on it.

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

N/A, but perhaps a Python registry? 😃

**Comment by pkwarren** [comment]
Reopening as we'd like to review this a bit more before release.

**Comment by jproffitt** [comment]
What is the status of this? I think this ticket is also requesting a `mypy-protobuf` plugin: 
https://github.com/bufbuild/plugins/issues/452
