### ISSUE TITLE
Plugin request for Buf Schema Registry - `protoc-gen-go-vtproto`

### ISSUE THREAD

**Issue by brancz** [bufbuild/plugins#251]
## Mandatory

**Where is the source code for the plugin?**

The source code for the [`protoc-gen-go-vtproto`](https://buf.build/planetscale/plugins/vtproto) plugin is found here:

https://github.com/planetscale/vtprotobuf

## Optional

**Does the plugin have a valid semver version?**

I believe so. `v0.3.0` is the latest version, taken from the GitHub tags: https://github.com/planetscale/vtprotobuf/tags

**Does this plugin have runtime dependencies?**

The only dependency is the canonical Go gRPC dependencies: `google.golang.org/grpc`

**Does the plugin have a dependency on another plugin?**

The `protoc-gen-go-vtproto` plugin depends on the base types produced by  `protoc-gen-go-grpc`.

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

I don't see why not, but I don't think I understand it enough to be able to say for sure.

**Comment by mfridman** [comment]
The plugin is now available as a Remote Plugin on the BSR at [community/planetscale-vtprotobuf](https://buf.build/community/planetscale-vtprotobuf).

Let us know if you have any issues.
