### ISSUE TITLE
Plugin request for Buf Schema Registry - ts-proto

### ISSUE THREAD

**Issue by brazelja** [bufbuild/plugins#253]
## Mandatory

https://github.com/stephenh/ts-proto

## Optional

**Does the plugin have a valid semver version?**

v.1.135.0 via the npm registry.

**Does this plugin have runtime dependencies?**

The plugin has the following runtime dependencies:

```json
"dependencies": {
  "@types/object-hash": "^1.3.0",
  "dataloader": "^1.4.0",
  "object-hash": "^1.3.1",
  "protobufjs": "^6.11.3",
  "ts-poet": "^6.2.0",
  "ts-proto-descriptors": "1.7.1"
}
```

**Does the plugin have a dependency on another plugin?**

Not currently

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

npm registry

**Comment by mfridman** [comment]
This has been added and will be kept up-to-date.

https://buf.build/community/stephenh-ts-proto

**Comment by mfridman** [comment]
Hey @brazelja , thanks for filing an issue. Do you know if this plugin supports outputting JavaScript?
