### ISSUE TITLE
Plugin request for Buf Schema Registry - timostamm/protobuf-ts

### ISSUE THREAD

**Issue by Rsdutta** [bufbuild/plugins#256]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/timostamm/protobuf-ts

## Optional

**Does the plugin have a valid semver version?**

v2.8.2 on BSR registry

**Does this plugin have runtime dependencies?**

[@protobuf-ts/runtime](https://www.npmjs.com/package/@protobuf-ts/runtime)

**Does the plugin have a dependency on another plugin?**

no

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**
yes

**Comment by timostamm** [comment]
Thank you @Rsdutta, I filled in the dependency information.
