### ISSUE TITLE
Plugin request for Buf Schema Registry - `protoc-gen-gofullmethods`

### ISSUE THREAD

**Issue by KenxinKun** [bufbuild/plugins#264]
## Mandatory

**Where is the source code for the plugin?**

Publicly released in https://github.com/90poe/protoc-gen-gofullmethods

## Optional

**Does the plugin have a valid semver version?**

Latest semver is 1.0.1, which can be obtained from the matching tag https://github.com/90poe/protoc-gen-gofullmethods/releases/tag/v1.0.1

**Does this plugin have runtime dependencies?**

No runtime dependencies

**Does the plugin have a dependency on another plugin?**

- google.golang.org/protobuf:v1.27.0

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

The plugin was compatible with the deprecated private plugins, so I expect it to be compatible with the go module proxy.
This plugin only generates Go code (intended to be used server side), so no relation to npm.

**Comment by pkwarren** [comment]
Before considering adding this to the BSR, can you please add a license file for the plugin in GitHub?

**Comment by KenxinKun** [comment]
PS: Note that I bumped to 1.0.1 after adding the license

**Comment by KenxinKun** [comment]
@pkwarren I think we can close this one, I worked with the grpc-go team and got a PR merged that achieves the functionality of this custom plugin. It will be available in March 2023 with the 1.54 release:
https://github.com/grpc/grpc-go/pull/5886

How quickly do the officially supported plugins get updated after each new release? (grpc-go in this case)

**Comment by mfridman** [comment]
Great! Thanks for the update, I'll close this issue.

> How quickly do the officially supported plugins get updated after each new release? (grpc-go in this case)

The short answer is within 1-2 days on average.

The long answer is ... there is a cron that runs once a day to poll new plugin versions. If new plugin versions are detected a PR is opened automatically against this repo. This requires a bit of manual triage (bumping docker image, ensures deps are up-to-date, etc.).

Once a PR is merged, it'll go out with the next release. A release is created once a day and from that point it's usually available on https://buf.build/plugins within 1-2 hours.
