### ISSUE TITLE
Plugin request for Buf Schema Registry: mypy-grpc-protobuf

### ISSUE THREAD

**Issue by lavikazarD** [bufbuild/plugins#360]
## Mandatory

https://github.com/jeffsawatzky/mypy-protobuf-bufbuild/blob/main/Dockerfile.protoc-gen-mypy_grpc
This is a derivative of:
https://github.com/nipunn1313/mypy-protobuf/tree/main/mypy_protobuf

**Does the plugin have a valid semver version?**

Yes, currently 3.4.0, from https://github.com/nipunn1313/mypy-protobuf/blob/main/CHANGELOG.md.

**Does this plugin have runtime dependencies?**

https://github.com/nipunn1313/mypy-protobuf#requirements-to-run-mypy-protobuf

**Does the plugin have a dependency on another plugin?**

Nope - it's commonly used with [python-protobuf](https://pypi.org/project/protobuf/), but isn't dependent on it.

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

Unsure? Let's chat!

**Comment by lavikazarD** [comment]
@pkwarren thanks!
When will it be deployed to the buf plugins page (aka: https://buf.build/plugins)?

**Comment by pkwarren** [comment]
> @pkwarren thanks! When will it be deployed to the buf plugins page (aka: https://buf.build/plugins)?

It takes them a short time to sync to all instances of the BSR. They now appear to be available.
