### ISSUE TITLE
Plugin request for Buf Schema Registry: protoc-gen-grpc-dotnet

### ISSUE THREAD

**Issue by jchadwick-buf** [bufbuild/plugins#409]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/grpc/grpc-dotnet

## Optional

**Does the plugin have a valid semver version?**

[v2.51.0](https://github.com/grpc/grpc-dotnet/releases/tag/v2.51.0)

**Does this plugin have runtime dependencies?**

Unsure (probably only on classes in grpc-dotnet itself)

**Does the plugin have a dependency on another plugin?**

Unsure (seems like it might generate the protobuf part as well?)

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

N/A

**Comment by pkwarren** [comment]
Closing request for now as there is nothing to be done - see https://github.com/bufbuild/plugins/issues/409#issuecomment-1460594256.
