### ISSUE TITLE
Plugin request for Buf Schema Registry - protoc-gen-twirp

### ISSUE THREAD

**Issue by mfridman** [bufbuild/plugins#58]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/twitchtv/twirp/tree/main/protoc-gen-twirp

## Optional

**Does the plugin have a valid semver version?**

`v8.1.2` found here: https://github.com/twitchtv/twirp/releases/tag/v8.1.2

**Does the plugin have default options?**

Not sure.

**Does this plugin have runtime dependencies?**

Yes, https://github.com/twitchtv/twirp. Note that the runtime does not follow Go modules, so it'll be something like:

```
v8.1.2+incompatible
```

**Does the plugin have a dependency on another plugin?**

I think so, it'll probably depend on `protoc-gen-go`

At least based on the docs here https://twitchtv.github.io/twirp/docs/install.html#code-generator

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

Not sure.

**Comment by QuantumGhost** [comment]
It seems that this plugin is not available in the [Remote Plugin](https://buf.build/plugins) list. Can I use this with remote plugin?

**Comment by pkwarren** [comment]
@QuantumGhost - Apologize for the confusion. This plugin was later removed as part of #153 prior to launch as we wished to make it work with remote packages. See #204 for an in progress follow up PR.

**Comment by pkwarren** [comment]
If this is picked up in the future, we need to ensure the plugin runs somehow with strategy `directory`: https://docs.buf.build/configuration/v1/buf-gen-yaml#strategy. It doesn't work reliably with `strategy=all` which is how remote plugins are executed. See https://github.com/bufbuild/buf/issues/1067 for more details.
