### ISSUE TITLE
Java package names in BSR

### ISSUE THREAD

**Issue by moritzzimmer** [bufbuild/plugins#636]
We are testing the the [maven remote packages](https://buf.build/docs/bsr/remote-packages/maven/) of the BSR. 

We are specifiying `java_package_prefix.default` in managed mode when generating java source code using `buf generate` which results in packages like `com.foo.bar` (`com` being the default, the rest originating from the proto package). 

The structure from the remote package on the other hand is `build.buf.gen.foo.bar` so we would need to change all import statements. Is there something we could configure so the java package structure in remote and locally generated packages is the same?

Thx and also thank's for the buf tooling in general!

**Comment by moritzzimmer** [comment]
should this questions be raised in https://github.com/bufbuild/buf instead?

**Comment by pkwarren** [comment]
Ok to ask questions here but the bufbuild/buf repo might get more visibility. Unfortunately, similar to other remote packages (like Go), you can't change the package path. We chose `build.buf.gen` for the public BSR as it wasn't expected to conflict with anything else and we do publish some artifacts to Maven central under `build.buf` groupId.

If you'd like to change the import paths, you have a few options:
1. Use remote plugins as you've been doing as `buf.gen.yaml` allows you to set the package path.
2. Use a plugin like `maven-shade-plugin` to relocate classes from `build.buf.gen.*` -> `com.foo.bar.*`: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html.
3. We publish source jars alongside our binary artifacts - you could always download the `-sources.jar` file produced for remote packages and unpack it and transform the code and compile your own artifact from that.

Hopefully one of these might work for you. We appreciate the feedback! We've gotten some requests similar to this to customize generated code for remote packages so may have a better solution in the future.

**Comment by moritzzimmer** [comment]
thx for the explanation @pkwarren. Guess we'll stick with remote plugins for now.
