### ISSUE TITLE
Plugin request for Buf Schema Registry: RoadRunner `protoc-gen-php-grpc` plugin

### ISSUE THREAD

**Issue by rustatian** [bufbuild/plugins#655]
## Mandatory

**Where is the source code for the plugin?**

- Link to the repository: [link](https://github.com/roadrunner-server/grpc/tree/master/protoc_plugins)
- Previously used `GitHub` action to push the plugin: [link](https://github.com/roadrunner-server/roadrunner/blob/v2.12.0/.github/workflows/release_grpc_buf.yml)

## Optional

**Does the plugin have a valid semver version?**

- `v2023.2.0`, version can be obtained from here: [link](https://github.com/roadrunner-server/roadrunner/releases)

**Does the plugin have a dependency on another plugin?**

- No

**Does the output of this plugin depend on any other external libraries?**

- No

**Comment by pkwarren** [comment]
This is now available - https://buf.build/community/roadrunner-server-php-grpc.

Thank you @rustatian for letting us know this was missing and also helping on the review!
