### ISSUE TITLE
Plugin request for Buf Schema Registry - protoc-gen-go-vtproto

### ISSUE THREAD

**Issue by mfridman** [bufbuild/plugins#73]
## Mandatory

**Where is the source code for the plugin?**

github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto

## Optional

**Does the plugin have a valid semver version?**

`v0.3.0` https://github.com/planetscale/vtprotobuf/releases/tag/v0.3.0

**Does the plugin have default options?**

N/A

**Does this plugin have runtime dependencies?**

N/A.

**Does the plugin have a dependency on another plugin?**

vtprotobuf is implemented as a helper plug-in that must be run alongside the upstream protoc-gen-go generato

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

N/A

**Comment by pkwarren** [comment]
Fixed by #79.

**Comment by bufdev** [comment]
Why did we add this? This isn't compatible with the go module proxy as currently implemented.
