### ISSUE TITLE
Plugin request for Buf Schema Registry: grpc/grpc-dart

### ISSUE THREAD

**Issue by tupats** [bufbuild/plugins#760]
Not ready to open an issue, but want to chat about your plugin? Come find us on our Public Slack channel:

https://buf.build/links/slack

## Mandatory

**Where is the source code for the plugin?**

https://github.com/grpc/grpc-dart

**Comment by pkwarren** [comment]
The existing https://buf.build/protocolbuffers/dart plugin already supports generating gRPC code if you specify the `grpc` option: https://pub.dev/packages/protoc_plugin#generating-grpc-headers

There is an end to end example of using gRPC with Dart here: https://grpc.io/docs/languages/dart/quickstart/
