### ISSUE TITLE
Plugin request for Buf Schema Registry for grpc-dart

### ISSUE THREAD

**Issue by ricebin** [bufbuild/plugins#834]
Not ready to open an issue, but want to chat about your plugin? Come find us on our Public Slack channel:

https://buf.build/links/slack

## Mandatory

**Where is the source code for the plugin?**

Example, the source code for the `protoc-gen-connect-go` plugin is found here:

https://github.com/grpc/grpc-dart

thanks!

**Comment by mfridman** [comment]
Hey there, please take a look at this https://github.com/bufbuild/plugins/issues/760#issuecomment-1697941615. There's not much for us to add here.

**Comment by ricebin** [comment]
thanks!
