### ISSUE TITLE
Plugin request for Buf Schema Registry - protobuf-c/protobuf-c

### ISSUE THREAD

**Issue by D00Movenok** [bufbuild/plugins#894]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/protobuf-c/protobuf-c

## Optional

**Does the plugin have a valid semver version?**

Yes, 1.4.1

**Does the plugin have a dependency on another plugin?**

No

**Does the output of this plugin depend on any other external libraries?**

No

**Comment by pkwarren** [comment]
To incorporate this, I think we'd want to wait for https://github.com/protobuf-c/protobuf-c/pull/673 to land in a current release (so we could build against recent versions of protobuf and on recent versions of our debian base images - https://github.com/protobuf-c/protobuf-c/issues/530).

How does this plugin compare to the upb project (https://github.com/protocolbuffers/protobuf/tree/main/upb#%CE%BCpb-small-fast-c-protos)?

**Comment by D00Movenok** [comment]
UPB is not recommended to use because it's not stable. Taken from https://github.com/protocolbuffers/protobuf/tree/main/upb#%CE%BCpb-small-fast-c-protos:

>
> While upb offers a C API, the C API & ABI are not stable. For this reason, upb is not generally offered as a C library for direct consumption, and there are no releases.
>

In addition, protobuf-c is well documented on the project wiki, unlike upb.

Also, the only example for usage of UPB can be found in official Python, Ruby and PHP protobuf implementations.

**Comment by mfridman** [comment]
There was a recent release upstream https://github.com/protobuf-c/protobuf-c/releases/tag/v1.5.0, more of an FYI.

**Comment by pkwarren** [comment]
This is now available: https://buf.build/community/protobuf-c
