### ISSUE TITLE
Plugin request for Buf Schema Registry - python-betterproto

### ISSUE THREAD

**Issue by mfridman** [bufbuild/plugins#95]
https://github.com/danielgtaylor/python-betterproto

**Comment by mfridman** [comment]
Closing for now. If this plugin becomes more popular we can re-open the issue.

**Comment by Darkheir** [comment]
We would love to have this plugin :-)
We are currently using the plugin we created https://buf.build/darkheir/plugins/python-betterproto but soon it's going to be an issue for us.

**Comment by ryaminal** [comment]
this is excellent, thanks everyone.

**Comment by simon-connektica** [comment]
Is there any chance you could publish v2.0.0-beta5? v1.2.5 dates back to 2020, the latest changes are available in v2.0.0-beta5 (and that is still almost 1 year old)

**Comment by Darkheir** [comment]
The issue is that the latest stable version is more than 3 years old and a lot of projects use the beta versions that are quite stable.

**Comment by simon-connektica** [comment]
I'm using this hack in the meantime...

```Dockerfile
FROM python:3.11-bullseye AS builder

RUN pip install "betterproto[compiler]==2.0.0b5" grpcio-tools

WORKDIR /app

CMD ls -lh /app/gen && python -m grpc_tools.protoc -I /app/proto --python_betterproto_out=/app/gen $(find /app/proto -iname '*.proto' | sort | xargs)
```

```sh
# Hack because betterproto 2.0.0b5 is not supported by buf yet
mkdir -p gen/python # required for correct ownership
docker build -f scripts/betterproto/Dockerfile -t proto-python-builder .
docker run --rm --user "$(id -u):$(id -g)" -v "$(pwd)/proto:/app/proto" -v "$(pwd)/gen/python:/app/gen" proto-python-builder
```

**Comment by mfridman** [comment]
It's pretty automated, there's a job that runs daily searching for updated plugin versions. Think of this repository as a "dependabot" for a Protobuf plugins.

Once a stable `semver is released, it'll get picked up automatically. The only condition is that it must be a valid semver without a pre-release component

Currently, `v1.2.5` is the latest stable version from https://github.com/danielgtaylor/python-betterproto/tags

Which is why it's the latest available one: https://buf.build/community/danielgtaylor-betterproto

I'm afraid until a stable v2.0.0 is released, we can't do much.
