### ISSUE TITLE
Plugin request for Buf Schema Registry - protoc-gen-go-json

### ISSUE THREAD

**Issue by mfridman** [bufbuild/plugins#97]
## Mandatory

**Where is the source code for the plugin?**

https://github.com/mitchellh/protoc-gen-go-json

## Optional

**Does the plugin have a valid semver version?**

[`v1.1.0`](https://github.com/mitchellh/protoc-gen-go-json/releases/tag/v1.1.0)

**Comment by bufdev** [comment]
This isn't compatible with the go module proxy as of now, and hasn't had new commits for almost a year - unless there's a request for it, I don't think we should add this.
